from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CameraCapturePost200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None, image_url=None):  # noqa: E501
        """CameraCapturePost200Response - a model defined in OpenAPI

        :param message: The message of this CameraCapturePost200Response.  # noqa: E501
        :type message: str
        :param image_url: The image_url of this CameraCapturePost200Response.  # noqa: E501
        :type image_url: str
        """
        self.openapi_types = {
            'message': str,
            'image_url': str
        }

        self.attribute_map = {
            'message': 'message',
            'image_url': 'image_url'
        }

        self._message = message
        self._image_url = image_url

    @classmethod
    def from_dict(cls, dikt) -> 'CameraCapturePost200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _camera_capture_post_200_response of this CameraCapturePost200Response.  # noqa: E501
        :rtype: CameraCapturePost200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this CameraCapturePost200Response.


        :return: The message of this CameraCapturePost200Response.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this CameraCapturePost200Response.


        :param message: The message of this CameraCapturePost200Response.
        :type message: str
        """

        self._message = message

    @property
    def image_url(self) -> str:
        """Gets the image_url of this CameraCapturePost200Response.

        URL to the captured image  # noqa: E501

        :return: The image_url of this CameraCapturePost200Response.
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url: str):
        """Sets the image_url of this CameraCapturePost200Response.

        URL to the captured image  # noqa: E501

        :param image_url: The image_url of this CameraCapturePost200Response.
        :type image_url: str
        """

        self._image_url = image_url
