from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CameraManualFocusPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, distance=None):  # noqa: E501
        """CameraManualFocusPostRequest - a model defined in OpenAPI

        :param distance: The distance of this CameraManualFocusPostRequest.  # noqa: E501
        :type distance: float
        """
        self.openapi_types = {
            'distance': float
        }

        self.attribute_map = {
            'distance': 'distance'
        }

        self._distance = distance

    @classmethod
    def from_dict(cls, dikt) -> 'CameraManualFocusPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _camera_manual_focus_post_request of this CameraManualFocusPostRequest.  # noqa: E501
        :rtype: CameraManualFocusPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def distance(self) -> float:
        """Gets the distance of this CameraManualFocusPostRequest.

        Focus distance in millimeters  # noqa: E501

        :return: The distance of this CameraManualFocusPostRequest.
        :rtype: float
        """
        return self._distance

    @distance.setter
    def distance(self, distance: float):
        """Sets the distance of this CameraManualFocusPostRequest.

        Focus distance in millimeters  # noqa: E501

        :param distance: The distance of this CameraManualFocusPostRequest.
        :type distance: float
        """

        self._distance = distance
