from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CameraExposurePostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, exposure_time=None):  # noqa: E501
        """CameraExposurePostRequest - a model defined in OpenAPI

        :param exposure_time: The exposure_time of this CameraExposurePostRequest.  # noqa: E501
        :type exposure_time: float
        """
        self.openapi_types = {
            'exposure_time': float
        }

        self.attribute_map = {
            'exposure_time': 'exposure_time'
        }

        self._exposure_time = exposure_time

    @classmethod
    def from_dict(cls, dikt) -> 'CameraExposurePostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _camera_exposure_post_request of this CameraExposurePostRequest.  # noqa: E501
        :rtype: CameraExposurePostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def exposure_time(self) -> float:
        """Gets the exposure_time of this CameraExposurePostRequest.

        Exposure time in milliseconds  # noqa: E501

        :return: The exposure_time of this CameraExposurePostRequest.
        :rtype: float
        """
        return self._exposure_time

    @exposure_time.setter
    def exposure_time(self, exposure_time: float):
        """Sets the exposure_time of this CameraExposurePostRequest.

        Exposure time in milliseconds  # noqa: E501

        :param exposure_time: The exposure_time of this CameraExposurePostRequest.
        :type exposure_time: float
        """

        self._exposure_time = exposure_time
