from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class LightsBlueMaxTimePostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, max_time=None):  # noqa: E501
        """LightsBlueMaxTimePostRequest - a model defined in OpenAPI

        :param max_time: The max_time of this LightsBlueMaxTimePostRequest.  # noqa: E501
        :type max_time: float
        """
        self.openapi_types = {
            'max_time': float
        }

        self.attribute_map = {
            'max_time': 'max_time'
        }

        self._max_time = max_time

    @classmethod
    def from_dict(cls, dikt) -> 'LightsBlueMaxTimePostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _lights_blue_max_time_post_request of this LightsBlueMaxTimePostRequest.  # noqa: E501
        :rtype: LightsBlueMaxTimePostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def max_time(self) -> float:
        """Gets the max_time of this LightsBlueMaxTimePostRequest.

        Maximum time in seconds the blue light can stay on  # noqa: E501

        :return: The max_time of this LightsBlueMaxTimePostRequest.
        :rtype: float
        """
        return self._max_time

    @max_time.setter
    def max_time(self, max_time: float):
        """Sets the max_time of this LightsBlueMaxTimePostRequest.

        Maximum time in seconds the blue light can stay on  # noqa: E501

        :param max_time: The max_time of this LightsBlueMaxTimePostRequest.
        :type max_time: float
        """

        self._max_time = max_time
